[package]
name = "brancher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15.0"
thiserror = "1.0"
crossterm = "0.25.0"
chrono = "0.4.22"
